yelp_project:
  target: dev
  outputs:
    dev:
      type: sqlserver
      driver: "ODBC Driver 18 for SQL Server"
      server: "is402server.database.windows.net"
      database: "is402db"
      schema: "dbo"
      user: "trieu"
      password: "Admin003@"
      port: 1433
      trust_cert: True

    spark:
      type: spark
      host: "https://adb-1192907376890899.19.azuredatabricks.net"
      http_path: "sql/protocolv1/o/1192907376890899/1130-201538-nhydu9vz"
      token: "dapia15faa9e0f232350b3844d69aa601ee8"
      catalog: "is402"
      schema: "default"
      threads: 1
